### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by rchl** [mozilla-iot/zwave-adapter#17]
Can you please make a new release? I'd like to test gateway but currently getting an error that seems to be fixed on master.

```
2018-03-21 21:58:36.260 zwave: Loading add-on for zwave-adapter from /home/pi/.mozilla-iot/addons/zwave-adapter
2018-03-21 21:58:36.290 zwave: { Error: Cannot find module 'serialport'
2018-03-21 21:58:36.291 zwave:     at Function.Module._resolveFilename (module.js:547:15)
2018-03-21 21:58:36.292 zwave:     at Function.Module._load (module.js:474:25)
2018-03-21 21:58:36.292 zwave:     at Module.require (module.js:596:17)
2018-03-21 21:58:36.293 zwave:     at require (internal/module.js:11:18)
2018-03-21 21:58:36.293 zwave:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/zwave-adapter/zwave-adapter.js:15:20)
2018-03-21 21:58:36.293 zwave:     at Module._compile (module.js:652:30)
2018-03-21 21:58:36.293 zwave:     at Object.Module._extensions..js (module.js:663:10)
2018-03-21 21:58:36.294 zwave:     at Module.load (module.js:565:32)
2018-03-21 21:58:36.294 zwave:     at tryModuleLoad (module.js:505:12)
2018-03-21 21:58:36.294 zwave:     at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
2018-03-21 21:58:36.295 zwave: Failed to register package: zwave-adapter with gateway
```

**Comment by mrstegeman** [comment]
Done.
